<?php

/**
 * @file
 * Contains exercise_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sitesettings_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sitesettings_api module.
    case 'help.page.sitesettings_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Axelerant Assignment.') . '</p>';
      return $output;

    default:
  }
}
